apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-red-pvc
  namespace: node-red
  labels:
    app: node-red
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
