apiVersion: v1
kind: Service
metadata:
  name: node-red-service
  namespace: node-red
  labels:
    app: node-red
spec:
  type: ClusterIP
  ports:
  - port: 1880
    targetPort: 1880
    protocol: TCP
    name: http
  selector:
    app: node-red
